# composition file configs sourced from https://github.com/veryacademy/docker-mastery-with-django/tree/main/Part-6%20Nginx%20React%20and%20Django%20Gunicorn/Final
version: '3'

services:
  backend:
    build:
      context: ./django
    command: gunicorn core.wsgi --bind 0.0.0.0:8000 --preload
    ports:
      - "8000:8000"
    volumes:
      - ./django:/django
    container_name: django-container

  frontend:
    build:
      context: ./react/frontend
    volumes:
      - react_build:/react/build
    container_name: react-container
    stdin_open: true

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    container_name: nginx-container
    depends_on:
      - backend
      - frontend

volumes:
  react_build: